Traceback (most recent call last):
  File "servidorUM.py", line 16, in <module>
    bd_addr = sys.argv[1]
IndexError: list index out of range
